user_validates:
  name_max: 50
  email_max: 255
  password_min: 6
gravatar:
  size: 80
  user_size: 50
page:
  page_item: 10
remember:
  yeah: "1"
time:
  hours_expired: 2
micropost:
  maximum: 140
resize_to_limit: [400, 400]
picture_size:
  size: 5
